### ISSUE TITLE
Mod makes game crash

### ISSUE THREAD

**Issue by GemaKuroNekoChan** [adambennett/Balatro-DeckCreator#3]
I've downloaded the mod and placed it on Mods folder, but one of these 2 errors occurs :
- the mod isn't recognize by the game
- the game crashes as soon as the game is launched

Can we have more informations on how to install this particular mod ?

**Comment by adambennett** [comment]
There isn't much else to explain. If you extract the zip into your mods folder, you should end up with a directory called Deck Creator with all my files inside. If you are running Steamodded it should load as expected.

Can you share details about the crash you are seeing when loading the mod?

**Comment by GemaKuroNekoChan** [comment]
I tried multiple things and it seems like putting everything in a single folder in mods folder is working, so I'm gonna use it for now, thanks btw for help !
