### ISSUE TITLE
Crash when swapping tab to "Base Deck"

### ISSUE THREAD

**Issue by l4dbill8745** [adambennett/Balatro-DeckCreator#5]
```functions/common_events.lua:1371: attempt to index field 'jokers' (a nil value)```

Other users in the discord have indicated a similar error when adding jokers to custom decks.

![image](https://github.com/adambennett/Balatro-DeckCreator/assets/37612093/ac0d8898-a082-4317-969b-5fc8126644d1)

**Comment by adambennett** [comment]
This crash should be resolved with v1.2.0. Please let me know if you continue to see this error and I'll reopen and investigate. Thanks!
