### ISSUE TITLE
Unable to perform arithmetic on global 'hand_chips' (a nil value)

### ISSUE THREAD

**Issue by oxiclean4x** [adambennett/Balatro-DeckCreator#6]
Trying to use the deck creator, but every time i play a hand, i get an error:
![bug](https://github.com/adambennett/Balatro-DeckCreator/assets/166090742/5a4b0420-eb74-4da1-8521-3f8420261293)
just wondering how to get this fixed so i can make some goofy decks

**Comment by MP-13-Soundwave** [comment]
I have this error too

**Comment by adambennett** [comment]
This can be fixed by updating to the latest version of Steamodded
